from enum import StrEnum


class Language(StrEnum):
    JAVA = "JAVA"
    TYPESCRIPT = "TYPESCRIPT"
    JAVASCRIPT = "JAVASCRIPT"
    PYTHON = "PYTHON"
    UNKNOWN = "UNKNOWN"


class NodeKind(StrEnum):
    PROJECT = "PROJECT"
    MODULE = "MODULE"
    PACKAGE = "PACKAGE"
    FILE = "FILE"
    CLASS = "CLASS"
    INTERFACE = "INTERFACE"
    ENUM = "ENUM"
    FUNCTION = "FUNCTION"
    METHOD = "METHOD"
    CONSTRUCTOR = "CONSTRUCTOR"
    FIELD = "FIELD"
    PROPERTY = "PROPERTY"
    TYPE_ALIAS = "TYPE_ALIAS"
    ENDPOINT = "ENDPOINT"
    EXTERNAL_DEPENDENCY = "EXTERNAL_DEPENDENCY"
    UNKNOWN = "UNKNOWN"


class EdgeKind(StrEnum):
    IMPORTS = "IMPORTS"
    CALLS = "CALLS"
    INHERITS = "INHERITS"
    IMPLEMENTS = "IMPLEMENTS"
    INJECTS = "INJECTS"
    USES = "USES"
    CREATES = "CREATES"
    READS = "READS"
    WRITES = "WRITES"
    DEPENDS_ON = "DEPENDS_ON"
    DATA_FLOWS_TO = "DATA_FLOWS_TO"
    TAINT_FLOWS_TO = "TAINT_FLOWS_TO"
    CROSSES_TRUST_BOUNDARY = "CROSSES_TRUST_BOUNDARY"


class GraphProjection(StrEnum):
    ARCHITECTURE_DEPENDENCY = "ARCHITECTURE_DEPENDENCY"
    CALL = "CALL"
    DATA_FLOW = "DATA_FLOW"
    SECURITY = "SECURITY"
