from enum import StrEnum


class DiscoveryStrength(StrEnum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    AMBIGUOUS = "AMBIGUOUS"


class ComponentRole(StrEnum):
    CONTROLLER = "CONTROLLER"
    SERVICE = "SERVICE"
    REPOSITORY = "REPOSITORY"
    DOMAIN_MODEL = "DOMAIN_MODEL"
    DOMAIN_SERVICE = "DOMAIN_SERVICE"
    ADAPTER = "ADAPTER"
    GATEWAY = "GATEWAY"
    CLIENT = "CLIENT"
    CONFIGURATION = "CONFIGURATION"
    UTILITY = "UTILITY"
    UNKNOWN = "UNKNOWN"


class DiscoveredLayer(StrEnum):
    PRESENTATION = "PRESENTATION"
    APPLICATION = "APPLICATION"
    DOMAIN = "DOMAIN"
    PERSISTENCE = "PERSISTENCE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    UNKNOWN = "UNKNOWN"
    AMBIGUOUS = "AMBIGUOUS"


class DiscoveryEvidenceKind(StrEnum):
    NAME_PATTERN = "NAME_PATTERN"
    PATH_PATTERN = "PATH_PATTERN"
    ANNOTATION = "ANNOTATION"
    DECORATOR = "DECORATOR"
    INHERITANCE = "INHERITANCE"
    IMPORT_PATTERN = "IMPORT_PATTERN"
    DEPENDENCY_DIRECTION = "DEPENDENCY_DIRECTION"
    GRAPH_POSITION = "GRAPH_POSITION"
    STRUCTURAL_SHAPE = "STRUCTURAL_SHAPE"
    MODULE_PATH = "MODULE_PATH"


STRENGTH_ORDER = {
    DiscoveryStrength.WEAK: 1,
    DiscoveryStrength.MODERATE: 2,
    DiscoveryStrength.STRONG: 3,
}
