from enum import StrEnum


class ParserLanguage(StrEnum):
    JAVA = "JAVA"
    TYPESCRIPT = "TYPESCRIPT"
    JAVASCRIPT = "JAVASCRIPT"
    TSX = "TSX"


class DiagnosticSeverity(StrEnum):
    ERROR = "ERROR"
    WARNING = "WARNING"


class ParserDiagnosticCode(StrEnum):
    SYNTAX_ERROR = "PARSER_SYNTAX_ERROR"
    MISSING_NODE = "PARSER_MISSING_NODE"
    UNSUPPORTED_LANGUAGE = "PARSER_UNSUPPORTED_LANGUAGE"
    SOURCE_READ_ERROR = "PARSER_SOURCE_READ_ERROR"
    DECODING_ERROR = "PARSER_DECODING_ERROR"
    SOURCE_INELIGIBLE = "PARSER_SOURCE_INELIGIBLE"
    RESOURCE_LIMIT = "PARSER_RESOURCE_LIMIT"
    EXECUTION_ERROR = "PARSER_EXECUTION_ERROR"
    DIAGNOSTICS_TRUNCATED = "PARSER_DIAGNOSTICS_TRUNCATED"


class ParseStatus(StrEnum):
    PARSED = "PARSED"
    INVALID = "INVALID"
    SKIPPED = "SKIPPED"
    UNSUPPORTED = "UNSUPPORTED"
    FAILED = "FAILED"


class ParseSkipReason(StrEnum):
    INELIGIBLE = "INELIGIBLE"
    DISABLED_LANGUAGE = "DISABLED_LANGUAGE"
    SIZE_LIMIT = "SIZE_LIMIT"
