from enum import StrEnum


class ReferenceKind(StrEnum):
    IMPORT = "IMPORT"
    EXTENDS = "EXTENDS"
    IMPLEMENTS = "IMPLEMENTS"
    CALL = "CALL"
    CREATE = "CREATE"
    TYPE_USE = "TYPE_USE"


class ImportKind(StrEnum):
    JAVA = "JAVA"
    ES_NAMED = "ES_NAMED"
    ES_DEFAULT = "ES_DEFAULT"
    ES_NAMESPACE = "ES_NAMESPACE"
    ES_SIDE_EFFECT = "ES_SIDE_EFFECT"
    COMMONJS = "COMMONJS"


class Visibility(StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    PROTECTED = "PROTECTED"
    DEFAULT = "DEFAULT"


class ResolutionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"
    EXTERNAL = "EXTERNAL"


class ResolutionMethod(StrEnum):
    EXACT_QUALIFIED = "EXACT_QUALIFIED"
    EXACT_IMPORT = "EXACT_IMPORT"
    SAME_FILE = "SAME_FILE"
    SAME_PACKAGE = "SAME_PACKAGE"
    EXPLICIT_RELATIVE_MODULE = "EXPLICIT_RELATIVE_MODULE"
    UNIQUE_CONTAINER = "UNIQUE_CONTAINER"
    STATIC_QUALIFIED = "STATIC_QUALIFIED"
    EXTERNAL_PACKAGE = "EXTERNAL_PACKAGE"
    NONE = "NONE"


class ExtractionDiagnosticCode(StrEnum):
    UNSUPPORTED_CONSTRUCT = "EXTRACT_UNSUPPORTED_CONSTRUCT"
    INVALID_STRUCTURE = "EXTRACT_INVALID_STRUCTURE"
    MISSING_EXTRACTOR = "EXTRACT_MISSING_EXTRACTOR"
    EXTRACTION_FAILED = "EXTRACT_FAILED"
    PARSE_ERRORS = "EXTRACT_PARSE_ERRORS"
    INVALID_FILE_SKIPPED = "EXTRACT_INVALID_FILE_SKIPPED"
    RESOLUTION_UNRESOLVED = "RESOLUTION_UNRESOLVED"
    RESOLUTION_AMBIGUOUS = "RESOLUTION_AMBIGUOUS"
    RESOLUTION_EXTERNAL = "RESOLUTION_EXTERNAL"
    RESOLUTION_CONFLICT = "RESOLUTION_CONFLICT"
    IAM_VALIDATION_ERROR = "IAM_VALIDATION_ERROR"
    PROVENANCE_LIMIT = "IAM_PROVENANCE_LIMIT"
